<?php
/**
 * @file
 * Code for the Donate feature.
 */

include_once 'hfl_donate.features.inc';

module_load_include('inc', 'hfl_donate', 'hfl_donate.form');

function hfl_donate_form_donate_entityform_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = '_hfl_donate_form_donate_entityform_edit_form_validate';
  $form['actions']['submit']['#submit'] = array_merge(array('_hfl_donate_form_donate_entityform_edit_form_submit'), $form['#submit']);
}

