<?php

/**
 * Implements hook_block_info().
 *
 * @return array
 */
function hfl_amazonwishlist_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('Amazon Wishlist'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 *
 * @return array
 */
function hfl_amazonwishlist_block_view($delta='') {
  $block = array();

  $block['content'] = '<SCRIPT charset="utf-8" type="text/javascript" src="http://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&MarketPlace=US&ID=V20070822%2FUS%2Fwidgetsamazon-20%2F8004%2F81d07a86-2ac5-4ddf-a91d-dcc157b3d4e2"> </SCRIPT> <NOSCRIPT><A HREF="http://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&MarketPlace=US&ID=V20070822%2FUS%2Fwidgetsamazon-20%2F8004%2F81d07a86-2ac5-4ddf-a91d-dcc157b3d4e2&Operation=NoScript">Amazon.com Widgets</A></NOSCRIPT>';


  return $block;
}
