<?php

/**
 * Implements hook_block_info().
 *
 * @return array
 */
function hfl_amazonwishlist_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('Amazon Wishlist'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 *
 * @return array
 */
function hfl_amazonwishlist_block_view($delta='') {
  $block = array();

  $block['content'] = '<SCRIPT
  charset="utf-8"
  type="text/javascript"
  src="http://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&MarketPlace=US&ID=V20070822%2FUS%2Fwidgetsamazon-20%2F8004%2F72774958-3642-4555-844d-137cb12763a0"></SCRIPT>
  <NOSCRIPT><A HREF="http://ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&MarketPlace=US&ID=V20070822%2FUS%2Fwidgetsamazon-20%2F8004%2F72774958-3642-4555-844d-137cb12763a0&Operation=NoScript">Amazon.com Widgets</A></NOSCRIPT>';


  return $block;
}
